# Generated by Django 4.2.6 on 2024-04-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionList',
            fields=[
                ('auc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('winner_id', models.IntegerField()),
                ('auc_payment', models.DecimalField(decimal_places=0, max_digits=10)),
                ('product_id', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('bidding_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('bid_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('prod_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=25)),
                ('cat_desc', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.IntegerField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_desc', models.CharField(max_length=400)),
                ('start_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller_id', models.IntegerField()),
                ('cat_id', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('zipcode', models.CharField(max_length=6)),
                ('user_name', models.CharField(max_length=20)),
                ('streetno', models.IntegerField()),
                ('streetname', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=30)),
                ('gmail', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
