# Generated by Django 4.2.6 on 2024-04-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlist',
            name='status',
        ),
    ]
